### ISSUE TITLE
[Feature]: 컴포즈에서 LazyLayout 사용할 때 overScroll effect 없애는 방법 검토하기

### ISSUE THREAD

**Issue by Sookhee** [mash-up-kr/mashup_Android#164]
### 기능

https://developer.android.com/reference/kotlin/androidx/compose/foundation/package-summary#LocalOverscrollConfiguration()

**Comment by jisungbin** [comment]
제가 담당해봐도 될까요? 진행일이 언제가 될 진 모릅니다.
