### ISSUE TITLE
[Bug]: 스케줄 이벤트 리스트 2줄로 만들기

### ISSUE THREAD

**Issue by jaeryo2357** [mash-up-kr/mashup_Android#251]
### 이미 제보된 버그인가요?

- [X] 제보된 버그인 지 찾아봤습니다.

### 무슨 버그인가요?

이벤트 제목이 길어질 경우 2줄로 표시되어야 할 것 같아요!

<img src="https://user-images.githubusercontent.com/33657541/221569245-c7607c39-3a62-4134-b097-83dc2b52ac27.png" width="40%">

**Comment by jisungbin** [comment]
marquee text도 좋은 방안 같습니당
